### ISSUE TITLE
API permission

### ISSUE THREAD

**Issue by lbznancio** [danielnaber/languagetool-for-framemaker#4]
Hi there, Daniel. I'm a TI student developing an educational project for my country (BR). For this, I'd like to use the Language Tool API, but only the API - which your pricing doesn't offer. So my question is: how much does your team would charge for only access the API of yours? Thank you. I looking forward to your feedback. 

my email: lbznancio@gmail.com

**Comment by danielnaber** [comment]
You could use the free API at http://wiki.languagetool.org/public-http-api which has some limitations (fewer requests, no premium rules) but should get you started. If you have questions about the free API, please post them to https://forum.languagetool.org.

**Comment by lbznancio** [comment]
Got it. But, if I want to use only the API (with premium rules), are you
(and your team) able to make a deal?

Em seg, 8 de out de 2018 às 10:34, Daniel Naber <notifications@github.com>
escreveu:

**Comment by danielnaber** [comment]
Please email to the address given at https://languagetoolplus.com/legal/
